# Generated by Django 4.1.6 on 2023-02-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('geometry', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='recentplan',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
