# Generated by Django 4.1.6 on 2023-02-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_location_alter_recentplan_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_id',
        ),
    ]
