# Generated by Django 4.1.6 on 2023-02-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_location_location_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
