# Generated by Django 4.1.6 on 2023-02-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_location_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint_default',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_time', models.IntegerField()),
            ],
        ),
    ]
