# Generated by Django 4.1.6 on 2023-03-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_appoint_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='planning_to_visualize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=255)),
                ('destin_name', models.CharField(max_length=255)),
                ('avg_time', models.PositiveIntegerField()),
                ('percent', models.PositiveIntegerField()),
            ],
        ),
    ]
