# Generated by Django 4.1.6 on 2023-03-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_planning_to_visualize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='planning_to_visualize',
        ),
        migrations.DeleteModel(
            name='recentplan',
        ),
    ]
