# Generated by Django 4.1.6 on 2023-03-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_planning_to_visualize_delete_recentplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='planning_to_visualize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=255)),
                ('destin_name', models.CharField(max_length=255)),
                ('avg_time', models.PositiveIntegerField()),
                ('percent', models.PositiveIntegerField()),
                ('pie_chart', models.ImageField(upload_to='')),
                ('bar_chart', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Recentplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('origin_name', models.CharField(max_length=255)),
                ('origin_pos', models.CharField(max_length=255)),
                ('destin_name', models.CharField(max_length=255)),
                ('destin_pos', models.CharField(max_length=255)),
                ('avg_time', models.PositiveIntegerField()),
                ('percent', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
