# Generated by Django 4.1.6 on 2023-03-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_planning_to_visualize_recentplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentplan',
            name='percent',
        ),
    ]
