# Generated by Django 4.1.6 on 2023-03-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_recentplan_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantype', models.CharField(max_length=255)),
                ('start', models.CharField(max_length=255)),
                ('arrv', models.CharField(max_length=255)),
                ('traveltime', models.CharField(max_length=255)),
            ],
        ),
    ]
