# Generated by Django 4.1.6 on 2023-03-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_planning_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planning_temp',
        ),
    ]
