# Generated by Django 4.1.6 on 2023-03-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_planning_temp_arrv_alter_planning_temp_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning_temp',
            name='arrv',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='planning_temp',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
