# Generated by Django 4.1.6 on 2023-03-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_planning_temp_arrv_alter_planning_temp_start'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planning_temp',
        ),
    ]
