# Generated by Django 4.1.6 on 2023-03-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planning_temp',
        ),
    ]
