# Generated by Django 4.1.6 on 2023-03-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_planning_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_id',
        ),
    ]
