# Generated by Django 4.1.6 on 2023-03-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_delete_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
