# Generated by Django 4.1.6 on 2023-03-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_varandma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Varandma',
        ),
    ]
