# Generated by Django 4.1.6 on 2023-03-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_varandma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Varandma',
        ),
    ]
