# Generated by Django 4.1.6 on 2023-03-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_delete_varandma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varandma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=255)),
                ('End', models.CharField(max_length=255)),
                ('days', models.CharField(max_length=8)),
                ('time', models.TimeField()),
                ('ff', models.FloatField()),
                ('avg', models.FloatField()),
                ('p95', models.FloatField()),
                ('tti', models.FloatField()),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
