# Generated by Django 4.1.6 on 2023-04-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
