# Generated by Django 4.1.6 on 2023-04-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoint_default',
        ),
        migrations.DeleteModel(
            name='Location_time',
        ),
        migrations.DeleteModel(
            name='planning_to_visualize',
        ),
    ]
