# Generated by Django 4.1.6 on 2023-06-12 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_delete_appoint_default_delete_location_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentplan',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
