# Generated by Django 4.1.6 on 2023-06-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_recentplan_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentplan',
            name='timestamp',
            field=models.CharField(max_length=255),
        ),
    ]
