# Generated by Django 4.1.6 on 2023-06-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_recentplan_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentplan',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
